メッセージを表示するためのコンポーネント
prapro-ou/castella-frontend pull request #28
Opened 2023-08-04 07:02 UTC by Jaja-UMA

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [x] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
メッセージを表示するためのコンポーネント
### 実装したところ
messageの内容をメッセージ用の枠に表示
メッセージのクリックで展開，省略
### 懸念点
とりあえず100文字以上以下で省略するかを判断しているが，それでいいのか
また，文字ではなく行数で省略した方がいいのではないか
### 関連するIssue([Closes #数字]で選択可能)
Close #9

2023-08-04 09:27 UTC, Wansuko-cmd requested changes
レビューしましたので修正お願いします

2023-08-04 09:27 UTC, Wansuko-cmd commented on features/components/Message.js
> +
use clientを頼む

2023-08-04 09:27 UTC, Wansuko-cmd commented on features/components/Message.js
> +    if(isExpanded==false && messageNum > 100){
あんまletを使って欲しくないのでif式でお願いします
```
const displayText = if () else ;
```

2023-08-04 09:27 UTC, Wansuko-cmd commented on features/components/test.css
> +  }
消しといて

2023-08-05 02:38 UTC, Wansuko-cmd commented
コード自体は問題なさそうですが、やはり昨日言った
- パッと見メッセージが伸縮可能かどうかがわからない
- そもそも伸縮機能いるのか
というところが気になるところです。

ですので
- UIを変更する
- 機能を削除する
かのどちらかをしていただけると助かります

2023-08-05 02:48 UTC, Wansuko-cmd reviewed
質問とTipsだけですので確認 or コメントお願いします

2023-08-05 02:48 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +      className='mx-auto mt-4 w-96 overflow-hidden whitespace-pre-line rounded-lg bg-primary p-4 text-left text-white shadow-md'
mx-autoとmt-4ってなんのために書いてるなどありますか？

2023-08-05 02:48 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +      ? value.slice(0, 100) + '...'
すんません、よく見たらsubstrが非推奨になってたので変えました
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/string/substr

2023-08-05 02:48 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +    isExpanded === false && messageNum > 100
細かいですがここは==よりも===にした方が良さげです（修正済み）
https://nishinatoshiharu.com/js-difference-equality/

2023-08-07 04:35 UTC, Jaja-UMA commented
連絡遅くなりました．
UI変更やってみたもののできなかったので，機能削除の方針で進めようと思います．

2023-08-07 04:56 UTC, Wansuko-cmd requested changes

2023-08-07 04:56 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +  const [isExpanded, setIsExpanded] = useState(false);
機能削除するなら消した方が良さそう

2023-08-07 04:56 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +      onClick={() => setIsExpanded(!isExpanded)}
同じく

2023-08-07 04:56 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/Message.js
> +    isExpanded === false && messageNum > 100
同じく

2023-08-07 04:56 UTC, Wansuko-cmd commented
こちらの修正お願いします

2023-08-07 05:13 UTC, Wansuko-cmd approved these changes

2023-08-07 05:13 UTC, Wansuko-cmd commented
LGTM

2023-08-07 05:13 UTC, merged