メッセージのカードの作成
prapro-ou/castella-frontend pull request #32
Opened 2023-08-07 19:37 UTC by Yuto-Kambara

## チェックリスト

- [ ] マージ元のブランチが正しいか(自分の作成したブランチか)
- [ ] マージ先のブランチが正しいか(基本はmain)
- [ ] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [ ] プルリクエストの名前を変更する
- [ ] 下の欄を埋める

# 概要
件名と本文の最初の数文字と件数表示するコンポーネント
件名と本文の最初を表示する関数とメッセージの件数のボタンの関数の二つを合わせて作っている。
### 実装したところ
features/talks/threads/messages/component
### 懸念点
件名と本文の最初を表示する関数では文字の位置に関してもう少し良い調整の方法があるかも知れない。
件数のボタンでは関数の書き方を間違えているかも知れない。
### 関連するIssue([Closes #数字]で選択可能)
closes #31

2023-08-07 23:21 UTC, Wansuko-cmd commented
今更いうのもアレだけど`features/message-component`ではなく`feature/message-component`のように複数形じゃない方がいいかも
今回は変えなくてもOK

2023-08-07 23:23 UTC, Wansuko-cmd commented
書いて欲しい場所は`features/talks/threads/components`なのでまた移動してもらえると助かる

2023-08-07 23:52 UTC, Wansuko-cmd commented
<img width="281" alt="スクリーンショット 2023-08-08 8 51 44" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/85b514fc-5922-4ab8-bb25-189c26140fe6">

多分今表示がこんな感じになってると思う
これを元にレビューしたい

2023-08-07 23:57 UTC, Wansuko-cmd commented
1. 色がない
見たところ`tailwind.config.js`に色を追加してなさそう
バックの色およびURLの色は存在しない（伝え忘れてたごめん）のでこちらを追加してもらえると助かる
```
  ...
  theme: {
    colors: {
      primary: '#99A866',
      default: '#49454F',
      thin: '#888888',
      white: '#FFFFFF',

      // 以下の二行を追加
      card: '#D8D8D8',
      url: '#6192BB',
    },
   ...
```

2023-08-08 00:18 UTC, Wansuko-cmd requested changes
もうちょい指摘したいけど色々書くと読みづらくなるため一旦ここまでを修正してほしい
文句や意見などあれば個別のコメントに書いてもらえると助かる

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +  is_new,
ほんとにごめん
引数名のの書き方が統一できてなかった
message_count -> messageCount
is_new -> isNew
に変更してくれると

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +  const bgColor = selected === true ? 'bg-primary' : 'bg-backcolor';
bg-backcolorが定義されてないからいい感じに変えてもらえると

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +    <div className={'relative rounded-lg w-64 h-24 ' + bgColor}>
ここはこんな感じに書いた方がかっこいいと思う
```
<div className={`relative rounded-lg w-64 h-24 ${bgColor}`}>
```

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +function writetext(subject, body, is_new, selected) {
関数名はUpperCamelCaseで頼みたい
今回だと`WriteText`みたいな

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <p className='relative top-2 left-4 text-xl '>{displaySubject}</p>
`relative`はできれば使わない方がいいと思う
今回の場合は使わずにできるはず

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
この行がある理由があまりわからないけどなんか理由とかある？

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      </div>
今回の場合は
1. borderだけを表すdivを用意する（42行目だけ）
2. subjectを入れてるdivの下にborderを描く
のどちらかになりそう

この調子でやるなら1で実装するのがおすすめ
この行が消えればsubjectとの距離感が縮まるからあとは`margin`をうまいこと活用すればいい感じの距離が表せれそう

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +//件名のサイズ
これは余談やけど関数にコメントを残すときはjsDocというのを利用するのもあり

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='absolute bottom-1 right-3'>
relative absoluteはあまり使わない方がいい
画面サイズが変わったりしたときに地獄を見ることがある
どちらかというと要素を重ねたりするときに使う

2023-08-08 00:18 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='absolute bottom-1 right-3'>
ここはそのまま縦に並べつつ、右寄せをすればOK

2023-08-08 00:25 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
この行 -> borderを挟んでる41, 43行のこと

2023-08-08 00:26 UTC, Wansuko-cmd commented
修正できたものは`Resolve conversation`を押してもらえると

2023-08-08 00:26 UTC, Wansuko-cmd commented
あと一つ修正するたびにCommitしていけば綺麗

2023-08-08 00:27 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +//件名のサイズ
直せという意味ではないのであまり気にせずに
ただ現状ここのコメントと関数が合っていないので利用者を困惑させる可能性があるため書くなら内容の更新をした方がいい

2023-08-08 06:04 UTC, Yuto-Kambara commented on features/talks/threads/messages/components/ThreadTile.js
> +//件名のサイズ
メモ書きに使ってたのを消し忘れてました､すいません消しておきます。

2023-08-08 06:09 UTC, Yuto-Kambara commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
あの境界線の位置を背景の中央にしたくてそうしてます。位置調整がうまくいかず苦肉の策でそうしたところはあるのでもっと良い方法があるかもとは思います。

2023-08-08 07:43 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
考えられる方法としては以下の通り

1. 上のタブに下向きのmarginを取る
2. 上のタブに下だけborderを持ってくる

2023-08-08 07:43 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
これだったらrelative使わずにできそう

2023-08-08 10:48 UTC, Yuto-Kambara commented on features/talks/threads/messages/components/ThreadTile.js
> +      <div className='relative top-2 flex justify-center'>
ありがとうございます。やってみます。

2023-08-08 10:52 UTC, Yuto-Kambara commented
大体の位置はある程度調整できたのですがsubjectの位置だけうまく調整できなくて…subjectの部分のクラスにmtを入れて下げようとすると背景ごと下がってしまうのですがどうすれば良いでしょうか。

2023-08-08 12:04 UTC, Wansuko-cmd commented
例えばカード全体にpaddingをかけるといいかもしれない

https://github.com/prapro-ou/castella-frontend/blob/main/features/talks/threads/messages/components/Message.js

これとか参考になるかと

2023-08-08 13:16 UTC, Yuto-Kambara commented
ありがとうございます。subjectがこれで調整できたかと思います。

2023-08-08 17:28 UTC, Yuto-Kambara commented
すいません押し忘れてました､押しておきます。

2023-08-09 03:43 UTC, Wansuko-cmd requested changes
この内容を一度修正してもらえると助かりますorz

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +      {WriteText(subject, body, isNew, selected)}
`<WriteText subject={subject} body={body} isNew={isNew} selected={selected}>`
のようにかけるはず

2023-08-09 03:43 UTC, Wansuko-cmd commented on tailwind.config.js
> +      card: 'DBDBDB',
#が抜けてると思う

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/ThreadTile.js
このファイルは消してもらえると助かる

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +  const subjectNum = subject.length;
subjectNumって直訳すると「件名の数字」ってなってわかりづらい気がする
そのまま`subject.length`でいいと思う

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +        {NumberOfReplies(messageCount, onClickMessageCount, selected)}
ここも`<NumberOfReplies>`で書けるはず

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +      <div className='mr-4 mt-1 flex flex-row-reverse'>
flexって万能だから、使いすぎると意図がわかりづらい感じもする
今回は単純に右寄せするだけだから別の方法を使うのもあり

https://zero-plus.io/media/css-right/#margin-left%E3%80%81margin-right%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%E3%81%A7%E6%96%87%E7%AB%A0%E3%82%92%E5%8F%B3%E5%AF%84%E3%81%9B

こういう方法で右寄せしてもいいかも

2023-08-09 03:43 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +  var color = 'text-thin';
varって変更可能かつ再宣言可能な変数ということであまり使わない方がいい（間違えてぶち壊してしまう可能性がある）

constで定義して、if式で分岐するのがおすすめの方法
```
const textColor = if(selected) 'text-white' else if(isNew) 'text-black' else 'text-thin'
const borderColor = selected ? 'border-white' : 'border-thin'
```

2023-08-09 07:26 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadTile.js
> +  var color = 'text-thin';
一行目のコードを入力するとエラーが出るのですがどうすれば良いでしょうか。

2023-08-09 07:37 UTC, Yuto-Kambara commented on features/talks/threads/messages/components/ThreadTile.js
すいませんローカルの状態で消してしまってる場合ってどうのようにブランチ側のファイルを消すのでしょうか。

2023-08-09 13:46 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +  var color = 'text-thin';
すまん、jsではif式対応してなかったのを失念してた

```
const textColor = selected ? 'text-white' : isNew ? 'text-black' : 'text-thin';
```

2023-08-09 13:54 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +  var color = 'text-thin';
ちょっと改行とか決めて読みやすくするのもあり
```
const textColor = (selected ? 'text-white')
                                  : isNew ? 'text-black'
                                  : 'text-thin';
```

2023-08-09 17:38 UTC, Wansuko-cmd requested changes
これを修正してくれたらあとは微調整で終わりそう
いろいろすまん

2023-08-09 17:38 UTC, Wansuko-cmd commented on app/page.js
> +        body={'サンバのリズムを知ってるかい'}
謎のリズム

2023-08-09 17:38 UTC, Wansuko-cmd commented on app/page.js
このファイルの変更内容はまた消してもらえると

2023-08-09 17:38 UTC, Wansuko-cmd commented on app/page.js
毎回消すの面倒だったら自分の環境だけ.gitignoreに書くのもあり
https://www.yoheim.net/blog.php?q=20160510

2023-08-09 17:38 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +    : 'text-thin';
改行させすぎな気もする・・・linterが勝手にやったんだろうか

個人的には`条件式 ? '〇〇'`というのが意味単位だと思うので、これのたびに改行したい

2023-08-09 17:38 UTC, Wansuko-cmd commented on tailwind.config.js
> +      card: '#DBDBDB',
すまん、指定ミスった
F5F5F5だといい感じの色になるかも

2023-08-09 17:38 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
これが書いてくれたコンポーネント（色だけ変えてる）

<img width="331" alt="スクリーンショット 2023-08-10 2 33 45" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/64e840f0-9df5-46f0-8151-e58bd2af653d">

デザイン案

<img width="440" alt="スクリーンショット 2023-08-10 2 34 05" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/bd675992-24f0-4ea5-a108-cc55636d72d6">

かなりデザイン案に近くていい感じ
- もうちょい文字とのmarginがあってもいいかも
- ボーダーをもう少し薄くしたい
- もうちょっと丸みを加えても良さそう

2023-08-09 19:38 UTC, Yuto-Kambara commented on app/page.js
> +        body={'サンバのリズムを知ってるかい'}
適当に打った部分が残ってしまってました,消しておきます

2023-08-09 19:41 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadTile.js
> +    : 'text-thin';
おそらくその機能が発動していて変更しても保存するとまたもとの形に戻ってしまうのですがその機能を無視して保存する方法ってありますか。

2023-08-10 04:50 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +    : 'text-thin';
じゃあどうしようもないか・・・

2023-08-10 04:50 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
> +    : 'text-thin';
設定をいじればなんとかなると思うけどそこまでするのは・・・という感じだから閉じておく

2023-08-10 04:51 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
divてのは本当は四角なのでborderが二重にかかってる
例えば`border-t`とかにするとか、上のdivと結合して`border-b`とかにすればOK

2023-08-10 11:49 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadTile.js
ありがとうございます、先ほどそれを試すと線は細くなったのですが元のデザイン案のような文と線との先頭の隙間というかずれみたいなものがなくなってしまって、どうすれば良いでしょうか。

2023-08-10 14:44 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadTile.js
marginやpaddingで調整するしかないな・・・
だから正直subjectの方のborderを使った方がいいかも

2023-08-11 14:18 UTC, Wansuko-cmd commented
うーん、ごめん
時間がなくて次のタスクに行って欲しいから俺が修正してもいい？

2023-08-11 16:40 UTC, Yuto-Kambara commented
了解です。次のタスクに取りかかりたいと思います。

2023-08-11 23:01 UTC, Wansuko-cmd commented
そう、それを頼みたい

2023-08-12 00:30 UTC, Wansuko-cmd approved these changes

2023-08-12 00:31 UTC, merged