DestinationTileの作成
prapro-ou/castella-frontend pull request #33
Opened 2023-08-08 02:31 UTC by KitauchiRyota

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [ ] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
DestinationTile.jsの作成
まだ完成していませんが，期限が迫っているので一旦提出します

### 実装したところ
DestinationTile関数と，それ用にUnreadMessgeCountに手を加えて新たな関数として同じファイル内に追加

### 懸念点
勝手にUnrMsgCntForDT関数を作成した点
幅高さは適当にした点
(selectedがtrueの時に)未読アイコンが背景と接している点
この関数からsvgの色を変えるのが自分にはかなり難しい点
自分の実装の場合selectedはisSelectedの方が自然な気がしますが，いかがでしょうか
作成する指定のパスにcomponentというファイルが無いような気がします

page.jsに確認用のコードが残っている
lintが実行できなかった

### 関連するIssue([Closes #18]で選択可能)

2023-08-08 03:32 UTC, Wansuko-cmd commented
どこかで詰まってる感じ？それとも忘れちゃってた感じ？

2023-08-08 04:19 UTC, KitauchiRyota commented
アイコンのsvgを受け取って色変更する，というのがなかなか難しいです．
そこ以外は大体できていると思うので，見ていただけたら幸いです．

2023-08-08 04:42 UTC, Wansuko-cmd commented
色が違うsvgを用意する形で大丈夫！

2023-08-08 04:53 UTC, KitauchiRyota commented
承知しました．
しかし，srcやaltで受け取るのが1種類なので今のままでは実装できないと思うのですが，何か方法はありますでしょうか．

2023-08-08 05:27 UTC, Wansuko-cmd commented
selectedていう引数を導入して貰えると助かります

2023-08-08 06:06 UTC, KitauchiRyota commented
自分の理解力が足りてなかったらすみませんが，やはりまだ解決方法が思いつきません．
自分が言いたかったのは，publicに色の違うsvgを用意したとしてもDestinationTileに渡すsrcが1種類だと，通常時と選択時の両方を表すのは厳しいのではないか，ということです．
引数で，src1,src2,alt,・・・というようにsrcを複数受け取っても良いということでしょうか．それとも何か良い方法がありますでしょうか．
またselectedを導入，とは新たに引数を追加するということでしょうか，それとも既存の指定された引数selectedを用いる形で，ということでしょうか．
何度も質問して申し訳ありませんがご教示ください．

2023-08-08 07:45 UTC, Wansuko-cmd commented
すまん、やらかしてた
そもそもsrcおよびaltは消してしまっても問題ない（コンポーネントの中で設定する）

selectedは、新たに追加するかたちでお願いしたい

2023-08-08 08:41 UTC, KitauchiRyota commented
承知しました．ありがとうございます．
コードの方はとりあえず完成してpushしたつもりなのですが，何かを間違えていたようでどこへpushされたのかが分からなくなってしまいました．
お手数をおかけして大変申し訳ないのですが，そちらで探してもらうことは可能ですか．

2023-08-08 09:13 UTC, Wansuko-cmd commented
ちょっと俺もわからないな・・・
```
git log
git branch
```
これらの実行結果ってどうなる？

2023-08-08 09:19 UTC, KitauchiRyota commented
見にくいですが・・・
**git logです**
`PS C:\Users\kitauchi\prapro-ou\castella-frontend> git log
commit c9232904357075c0913252d9a9c457e56c147b78 (HEAD -> main)
Author: KitauchiRyota <136436225+KitauchiRyota@users.noreply.github.com>
Date:   Tue Aug 8 17:08:59 2023 +0900

    選択時のアイコンの色反転以外完了

commit 5940852d8d42a6a1e5f337f1d1a20720b40cc301
Author: KitauchiRyota <136436225+KitauchiRyota@users.noreply.github.com>
Date:   Tue Aug 8 10:32:12 2023 +0900

    DestinationTile用のUnreadMessageCountを作成

commit 587e839e3dfcd5e76d92bad0527afe1dcaef76ea
Author: KitauchiRyota <136436225+KitauchiRyota@users.noreply.github.com>
Date:   Tue Aug 8 10:05:50 2023 +0900

    selectedで色変更

commit 7407ff713289c7c42502bb62548fb03d55d87ce4
Author: KitauchiRyota <136436225+KitauchiRyota@users.noreply.github.com>
Date:   Tue Aug 8 08:20:46 2023 +0900

    アイコン，名前，未読数の横並び

commit 3de2dcd66d200c5d8d998996aac5f2901e147926
Merge: ef88728 020c208
Author: KitauchiRyota <136436225+KitauchiRyota@users.noreply.github.com>
Date:   Tue Aug 8 06:18:12 2023 +0900

    Merge branch 'main' of https://github.com/prapro-ou/castella-frontend

commit 020c208b9ef090548c83c0e628f2d68d8973d69d (origin/main, origin/HEAD)
Merge: 09dc6d9 930a110
Author: bugdog24 <63241922+Wansuko-cmd@users.noreply.github.com>
Date:   Mon Aug 7 21:33:56 2023 +0900
`

**こちらがgit branchです**
`PS C:\Users\kitauchi\prapro-ou\castella-frontend> git branch
  feature/component-FloatActionButton
  feature/talks/component-DestinationTile
  fix/eslint
* main`

2023-08-08 09:33 UTC, Wansuko-cmd commented
mainブランチで作業しちゃってる

2023-08-08 09:34 UTC, Wansuko-cmd commented
多分pushに成功したのは`branchを作った`という内容だけをpushできたからだと思われる
> git checkout -b feature/talks/component-DestinationTile
これでどうなる？

2023-08-08 09:42 UTC, KitauchiRyota commented
`PS C:\Users\kitauchi\prapro-ou\castella-frontend> git checkout -b feature/talks/component-DestinationTile`
` fatal: a branch named 'feature/talks/component-DestinationTile' already exists`

こうなりました

2023-08-08 10:01 UTC, Wansuko-cmd commented
```
git checkout feature/talks/component-DestinationTile
```

こうした後でコードを確認してみて
もし何も追加したコードがなければ以下のコマンドを実行してみて

```
git checkout main
git branch -D feature/talks/component-DestinationTile
git checkout -b feature/talks/component-DestinationTile
```

要は`feature/talks/component-DestinationTile`が存在する（多分コード変更は反映されてない）から一旦削除してみてもう一度作り直す感じ

2023-08-08 10:14 UTC, KitauchiRyota commented
ありがとうございます！できたと思います！そちらからも見られますか？

2023-08-08 10:44 UTC, Wansuko-cmd commented
見れた！ので後でレビューします

2023-08-08 12:07 UTC, Wansuko-cmd commented
新しいコードコミットできてない？

2023-08-08 12:20 UTC, Wansuko-cmd requested changes
レビューしました
修正などをお願いしますorz

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +function UnreadMessageCountForDT({ count,size,isSelected }) {
ここ、申し訳ない
本家UnreadMessageCountを以下のように修正する形にしてほしい
- 反転するかどうかを表す引数 reversedを導入して、trueの場合反転する
- reversedのデフォルト値はfalse(何も入力していなければfalseとなる)

2023-08-08 12:20 UTC, Wansuko-cmd commented on app/page.js
> +      <DestinationTile src='./add_white.svg' alt='a' name='DM' messageCount='3' selected={false} />
このページの差分は消してもらえると

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +                <Icon src={src} alt={alt} />{/*選択時の色変更は未実装 */}
ここって確か人型アイコンにするって話になっていた気がする

https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Aperson%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +                <Icon src={src} alt={alt} />{/*選択時の色変更は未実装 */}
Figmaから取ってきてもOK

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +                {/*<UnreadMessageCount count={messageCount}>*/}
コメントアウトは基本的に消したほうが良さそう

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +        <div className={`relative flex h-8 w-36 items-center rounded-lg ${selected ? 'bg-primary' : ''}`}> {/* ` バッククォートと ' シングルクォートの違いに注意*/}
relative absoluteは使わなくてもできそう？
書いた理由とかあると書いて欲しい

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +        <div className={`relative flex h-8 w-36 items-center rounded-lg ${selected ? 'bg-primary' : ''}`}> {/* ` バッククォートと ' シングルクォートの違いに注意*/}
<img width="183" alt="スクリーンショット 2023-08-08 21 14 29" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/fca859b1-1fa7-4fb8-855f-da04cbace7c6">

俺の画面だとこんな感じに出てきた

デザイン案
<img width="370" alt="スクリーンショット 2023-08-08 21 17 00" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/44bc8d67-a81b-46d1-93f0-65a8a5342cc0">


- もう少し端っこを丸くしても良さそう
- paddingなどを入れても良さそう
- 大きくしても良さそう

2023-08-08 12:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +    {/*UnreadMessageCountForDestinationTile 元の関数内のマジックナンバーを書き換えて良いか判断しかねたので代替案として実装 */ }
サイズは変えてもらってもOK
デザイン案で結局ここでしか使わない設計になりそうだし、ここを基準にした方が良さそうなのもある

2023-08-09 16:59 UTC, KitauchiRyota commented on features/talks/threads/messages/components/DestinationTile.js
> +        <div className={`relative flex h-8 w-36 items-center rounded-lg ${selected ? 'bg-primary' : ''}`}> {/* ` バッククォートと ' シングルクォートの違いに注意*/}
nameの長さに関わらず未読アイコンの位置を指定したかったので，ネットで調べて真似した感じです．
relative absolute消してみると左詰めになってしまったんですが，無しでもいけるものなんですか？

2023-08-09 18:02 UTC, KitauchiRyota commented
どの関数の機能にすべきかは悩み所ですが，未読件数が0の時に未読アイコンを表示させない機能も必要だと思います．

2023-08-10 01:16 UTC, Wansuko-cmd commented
上のResolved conventionボタンを押してもらえると

2023-08-10 01:20 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +        <div className={`relative flex h-8 w-36 items-center rounded-lg ${selected ? 'bg-primary' : ''}`}> {/* ` バッククォートと ' シングルクォートの違いに注意*/}
未読アイコンを右詰に指定すればいけると思う

2023-08-10 01:22 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +        <div className={`relative flex h-8 w-36 items-center rounded-lg ${selected ? 'bg-primary' : ''}`}> {/* ` バッククォートと ' シングルクォートの違いに注意*/}
https://zero-plus.io/media/css-right/

こことか見てみるといいかも

2023-08-10 14:40 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +    const src = selected ? './personIcon_white.svg' : './personIcon_black.svg';
ここだけど、実はimport文で書くことで直接ファイルを指定することも可能

例
```
import personIcon from 'public/personIcon_white.svg';

  const src = selected ? personIcon : './personIcon_black.svg';
```

2023-08-10 14:42 UTC, Wansuko-cmd approved these changes
コードもいい感じ、デザインもいい感じ
LGTM

2023-08-10 14:42 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +  const src = selected ? './personIcon_white.svg' : './personIcon_black.svg';
（Tips）ここ実はimport文を書くことで直接ファイルを指定できる

例
```
import personIcon from 'public/personIcon_white.svg';
...
const src = selected ? personIcon : './personIcon_black.svg';
```

2023-08-10 14:42 UTC, merged