Feature/thread screen
prapro-ou/castella-frontend pull request #41
Opened 2023-08-14 08:38 UTC by Yuto-Kambara

## チェックリスト

- [ ] マージ元のブランチが正しいか(自分の作成したブランチか)
- [ ] マージ先のブランチが正しいか(基本はmain)
- [ ] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [ ] プルリクエストの名前を変更する
- [ ] 下の欄を埋める

# 概要
スレッドの並ぶ画面の作成
### 実装したところ
feature/Talks/Threads/Component
### 懸念点
配列の中身の型がこれで合っているのか分からない。
### 関連するIssue([Closes #数字]で選択可能)
Issue [#38 ]

2023-08-14 10:17 UTC, Wansuko-cmd requested changes
この部分の修正をお願いします

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +    </div>
変数多いと読むときに覚えること多いし、そこまで複雑でもないから直接返す値にぶち込んでもOK

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +export default function ThreadScreen({ threads, onClickCreateThreadBotton }) {
Botton -> Button

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +      <div className=' grid-cols-1 space-y-10'>{list}</div>
classNameの後の空白の削除を頼む

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +        <FloatActionButton />
FloatActionButtonにonClickがある（mainブランチの方で追加されてた）のでそれを呼び出す形にしてほしい

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +        <FloatActionButton />
画像を渡す必要があるため、Figmaで設定してる画像を入れて反映させてくれると

```js
 FloatActionButton({
  src,
  alt,
  onClickButton = () => {},
})
```

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +      <div className=' grid-cols-1 space-y-10'>{list}</div>
gridってどういう意図で入れたとかある？

2023-08-14 10:17 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +  const list = threads.map((threads, index) => (
mapを使うのはいい感じ👍

2023-08-14 15:39 UTC, Wansuko-cmd commented
それであってる
git pullを忘れてない？

2023-08-14 16:39 UTC, Yuto-Kambara commented
git pull origin mainと打ってgit pullすると変なマージが発生してコミットしなければいけなくなるのですがこれはどこか間違っているのでしょうか

2023-08-15 01:30 UTC, Wansuko-cmd commented
エラーコードとか見せてくれると助かる（個人情報流れるかもだからSlackの方でお願い）

2023-08-15 01:32 UTC, Wansuko-cmd commented
基本的には
```
git fetch origin main
git pull origin main --no-ff
```
これでいけると思う

なんかコードの編集しちゃってる場合はその編集内容をコミットするなりする必要がある 
コードを残す場合 -> `git add .` `git commit  -m ""`
コードを消す場合 -> `git checkout .`

2023-08-15 07:13 UTC, Yuto-Kambara commented
了解です。slackでエラーの内容と共に質問させていただきます。

2023-08-15 12:17 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadScreen.js
> +        <FloatActionButton />
figmaから画像をダウンロードしてきてpublicのところに置いてそれを使うという感じでしょうか

2023-08-15 14:44 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +      <div className=' grid-cols-1 space-y-10'>{list}</div>
なるほど・・・
gridってこんな感じにレスポンシブ等に対応するときに使う印象が強い

https://www.webcreatorbox.com/tech/css-grid-basic-layout

これだったらflexでいけそう感がある

2023-08-15 15:26 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadScreen.js
> +      <div className=' grid-cols-1 space-y-10'>{list}</div>
了解です。flexに変更しておきます。

2023-08-15 23:52 UTC, Wansuko-cmd commented
まずはこれをpullしてもらえると

2023-08-15 23:56 UTC, Wansuko-cmd requested changes
まずはpullしてからこれらを修正してもらえると助かります

2023-08-15 23:56 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +      >
ここのbuttonは消せそう

2023-08-15 23:56 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +  const list = threads.map((threads, index) => (
map内の引数名がthreadsなのはちょっと違和感
threadみたいに単数系の方が良さそう？

2023-08-15 23:56 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +    <div key={index}>
[Tips]mapのkeyにindexを使うのはあまりよろしくない

https://zenn.dev/luvmini511/articles/f7b22d93e9c182

後日idの概念をぶち込むのでそれまではこれで行こう

2023-08-15 23:56 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadScreen.js
> +        {ThreadTile (threads)}
```
<ThreadTile />
```

みたいな形に変換できそう

2023-08-15 23:56 UTC, Wansuko-cmd commented on public/plus.svg
plus_white.svgの方が良さそう

2023-08-16 12:33 UTC, Yuto-Kambara commented
すみませんpullしたときに変更のあったファイルをコミットしないとpush出来なくて、なので変更したファイルという余計なコミットが入っています。

2023-08-16 12:57 UTC, Yuto-Kambara commented on features/talks/threads/component/ThreadScreen.js
> +        {ThreadTile (threads)}
上記のように打つとおそらく変数が伝わってないという内容のエラーが出るのですがどのように入力すれば良いでしょうか。

2023-08-17 08:05 UTC, Wansuko-cmd approved these changes

2023-08-17 08:07 UTC, Wansuko-cmd commented
将来的に直したいところ
- 横幅
- ボタンの位置？
ただこれは配置してみてから決めたい

2023-08-17 08:07 UTC, Wansuko-cmd commented
LGTM

2023-08-17 08:08 UTC, merged