サイドバーにて送信者一覧を表すコンポーネントの作成
prapro-ou/castella-frontend pull request #42
Opened 2023-08-14 10:47 UTC by KitauchiRyota

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [x] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
サイドバーで送信者の一覧を表すコンポ―ネント

### 実装したところ
`DestinationTile`で，未読件数が0以下の時は未読アイコンを表示させないように変更
`DestinationList`

### 懸念点
`AddButton`の表示に‘Icon‘コンポーネントをそのまま使い，左の”DM”という文字もそれに合わせたので，サイズが微妙かもしれない．

### 関連するIssue([Closes #数字]で選択可能)
Closes #2

2023-08-14 15:06 UTC, Wansuko-cmd requested changes
これらの修正をお願いします
コード自体は結構いい感じにかけてきてると思う👍

2023-08-14 15:06 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +      )}
ここはif文の方がいいかもしれない（else文がない文スッキリする）

2023-08-14 15:06 UTC, Wansuko-cmd commented on features/talks/threads/component/DestinationList.js
> +        <div className='text-3xl text-default'>DM</div>
DMの文字をもう少し小さくしてもいいかも

<img width="303" alt="スクリーンショット 2023-08-14 23 58 30" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/1a54837a-8ae0-4ca8-a204-f9c203896045">

作成してくれたUIが上で

<img width="416" alt="スクリーンショット 2023-08-14 23 58 25" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/b78c7481-ac37-49e0-8808-3af21582eb41">

原案がこんな感じ

2023-08-14 15:06 UTC, Wansuko-cmd commented on features/talks/threads/component/DestinationList.js
> +        <div className='text-3xl text-default'>DM</div>
なんか思ったよりもDestinationTileの余白も足りてない・・・？
そこも修正できそうならお願いしたい（本来はプルリク分けるべきではあるけど）

2023-08-14 20:32 UTC, KitauchiRyota commented on features/talks/threads/messages/components/DestinationTile.js
> +      )}
こちらなんですが，return文の中ではif文を使えない，というような記事を見たのでこのような実装にしました．
ifの部分をreturn文の外に出すという方法についても，良さげな実装が思いつかなかったのでこのように代替しました．
おっしゃる通りifで書けたらスッキリすると思います．しかし先輩が示されたコードも，該当箇所にコピペしただけでは上手く動かせませんでした．何かやり方があるのでしょうか．

2023-08-14 20:54 UTC, KitauchiRyota commented
指摘はされていませんでしたが，気になった点があるので伝えておきます．
`destinations`を`map`関数で処理する部分についてです．`map`関数の使い方がいまいちわかっていなかったのでとりあえず`key`を`item.name`としました．しかし後から他の人のコードを見たところ，`index`にすべきなのではないかと思いました．（現状だとメール相手に同姓同名はいないということになっている・・・？）懸念点の欄に書くべきでしたが，PRを作成した後で気づいたことですのでこういった形になってしまいました．これについて助言をいただきたいです．

2023-08-14 21:53 UTC, KitauchiRyota commented on features/talks/threads/component/DestinationList.js
> +        <div className='text-3xl text-default'>DM</div>
DMの文字についてですが，DMの文字の右にある＋アイコンを`Icon`コンポーネントで表示させている関係でこうなっています．`Icon`は出力される大きさが関数の内部で決まっている（と思います）ので，それにDMの文字のサイズも合わせた結果こうなりました．確かに僕も文字をもう少し小さくすれば良くなると思います．こちらを修正する際にはどのようにすればよいでしょうか（`Icon`コンポ―ネントを用いずに表示させる，`Icon`コンポーネントを変更，・・・）．

`DestinationTile`の修正についてはできると思いますのでやっておきます．

2023-08-15 01:35 UTC, Wansuko-cmd commented
気づいてしまったか・・・
俺もそれ見落としてたんだよな
https://zenn.dev/luvmini511/articles/f7b22d93e9c182

この記事を見ると今のname方式の方がまだ良さそう
一応将来的にidを渡すことになる（バックエンドから特定のDMの内容をとってくるために必要）のでそれを設定する形になるかと

2023-08-15 01:36 UTC, Wansuko-cmd commented on features/talks/threads/component/DestinationList.js
> +  // Destinationsの頭文字を小文字のdにするとmap関数でエラー
DestinaionListを使う側（多分`page.js`）の値を変更するのを忘れてたり？

2023-08-15 01:40 UTC, Wansuko-cmd commented on features/talks/threads/component/DestinationList.js
> +        <div className='text-3xl text-default'>DM</div>
Iconって確かユーザーの写真とかを表示するために利用するコンポーネントだったはず
だから今回はこいつを外す形でお願いしたい

2023-08-15 01:59 UTC, Wansuko-cmd commented on features/talks/threads/messages/components/DestinationTile.js
> +      )}
穴があったら入りたい

例えばこういう書き方が有効らしい
```
{messageCount > 0 && <UnreadMessageCount />}
```

2023-08-15 23:40 UTC, KitauchiRyota commented on features/talks/threads/component/DestinationList.js
> +  // Destinationsの頭文字を小文字のdにするとmap関数でエラー
あっ・・・
多分それでした．
ありがとうございます．

2023-08-16 00:07 UTC, KitauchiRyota commented on features/talks/threads/component/DestinationList.js
> +  const add_src = './add_black.svg';
たしかにパスを文字列として変数に入れて扱うのは乱暴すぎるなと思って変えようと思ったんですが，どうやら`public`のファイルは`import`では参照できない？ようです．（↓の「**srcフォルダにある画像を参照する方法**」の見出しの3行目くらい）
https://zenn.dev/kiriyama/articles/20480ad223d36e
`import`も書いてみましたがやはりうまくできませんでした．ただ色々試したわけでないので何か方法があるのかもしれません

2023-08-16 00:14 UTC, Wansuko-cmd commented on features/talks/threads/component/DestinationList.js
> +  const add_src = './add_black.svg';
https://github.com/prapro-ou/castella-frontend/blob/main/features/talks/threads/messages/components/MessageScreen.js#L5C49-L5C49

こいつを見てくれ
これってそっちだと動く？

2023-08-16 00:20 UTC, KitauchiRyota commented on features/talks/threads/component/DestinationList.js
> +  const add_src = './add_black.svg';
出来ました！パスの書き方を間違えていました．
ありがとうございます．

2023-08-16 07:35 UTC, Wansuko-cmd approved these changes

2023-08-16 07:35 UTC, merged