新着メッセージコンポーネントの作成
prapro-ou/castella-frontend pull request #45
Opened 2023-08-15 13:00 UTC by 1daLearn

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [x] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
<img width="610" alt="スクリーンショット 2023-08-12 15 07 10" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/4c371f8e-6bbf-416b-b096-6d711a9ad50a">

この青い棒を作成する

### 実装したところ
関数「ThreadsWithNewMessagesDivider」を実装．フレックスアイテムを定義して中央に「新着メッセージ」と出力する
### 懸念点
文字入力欄（「新着メッセージ」）を変数化すれば別の用途にも使えるかもしれない．
サイズ感が間違っているかもしれない．
動作テストの仕方が今だ分からないので，全部間違っている可能性すらあります．
### 関連するIssue([Closes #数字]で選択可能)

2023-08-15 13:12 UTC, Wansuko-cmd requested changes
この部分の修正をお願いします

2023-08-15 13:12 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <hr className='flex-grow border-t url' />
色を変えて欲しい
https://tailwindcss.com/docs/border-color

2023-08-15 13:12 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <span className='mx-4 url'>"新着メッセージ"</span>
""はいらなそう

2023-08-15 13:12 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +    <div className='flex items-center mt-4'>
ここのmt-4はいらなそう

2023-08-15 13:12 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <hr className='flex-grow border-t url' />
hrだしborder-tいらなさそう？

2023-08-15 13:58 UTC, 1daLearn commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <hr className='flex-grow border-t url' />
urlの部分すべてですか？

2023-08-15 14:39 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <hr className='flex-grow border-t url' />
デザイン案は青色なのでそれに合わせて欲しい

2023-08-15 23:58 UTC, Wansuko-cmd requested changes
色に関してこのように修正お願いします

2023-08-15 23:58 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <hr className='flex-grow border-blue-500' />
色なんだけどborder-blue-500って使えなかったはず
`tailwind.config.js`で定義されてる`url`を利用してほしい
blue-500 -> urlに置換する形で利用可能

2023-08-16 07:39 UTC, Wansuko-cmd requested changes
以下の部分の修正をお願いします

2023-08-16 07:39 UTC, Wansuko-cmd commented on features/talks/threads/component/ThreadsWithNewMessagesDivider.js
> +      <span className='mx-4 border-url'>新着メッセージ</span>
新着メッセージは文字だからborder-urlじゃなくてtext-urlにする必要がある

2023-08-16 17:18 UTC, Wansuko-cmd commented
LGTM

2023-08-16 17:18 UTC, Wansuko-cmd approved these changes

2023-08-17 01:54 UTC, merged