新規メッセージ作成用のモーダルの作成
prapro-ou/castella-frontend pull request #48
Opened 2023-08-19 07:03 UTC by KitauchiRyota

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [x] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
メッセージ画面で＋ボタンを押したときに出てくるモーダルの作成

### 実装したところ
`MessageDialog`

### 懸念点
関数，ファイル，ブランチの名前の付け方，ファイルの場所がいまいちかもしれない
テンプレートをほぼそのまま利用してデザインを変えていない点
コード整形ができていない

### 関連するIssue([Closes #数字]で選択可能)
Closes #40

2023-08-19 08:40 UTC, Wansuko-cmd requested changes
結構いい感じ
この点だけ修正してくれると助かる

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
Web文化詳しくないから絶対とは言えないけれど・・・
open, setOpenを渡してもらうよりは以下のようにした方がいいかも

```
open: boolean
onClickCancel: () -> Unit
onClickSend: ({body: string}) -> Unit
```

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
onClickCancel -> キャンセルボタンを押したときの挙動とかも設定したい時がある

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
setOpenを使わない -> アンチパターンに近い・・・要はいろんなところでsetOpenを呼ばれる可能性があってごっちゃになるかもしれないからやめといたほうがいいって感じ

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
[ここからは詳細なTipsだから読まなくてもOK]

setOpenに対しては「単方向データフローの原則に違反しているからNG」という言い方ができる。

フロントエンドの綺麗なコードは大体以下の二つに分割できる

- 表示するデータを管理するところ（通信部分とか）
- データを画面に表示するところ（コンポーネント等々）

データ管理を専門とする場所があるにもかかわらず、コンポーネントからデータ操作しちゃうと無法地帯になっちゃうからだめって感じ

そうじゃなくて「表示するデータを管理するところ」から「データを画面に表示するところ」へと一方的にデータ（と、データを変更する関数）を送り付けた方が管理が楽になる

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
詳しくは以下のURL
一番わかりやすいと思うけどこれAndroidなんよな・・・

https://developer.android.com/topic/architecture/ui-layer?hl=ja

2023-08-19 08:40 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +              Please write a new reply here!
日本語でお願いしたい
もしくはこういうのをやってもいいかも
https://zenn.dev/mybest_dev/articles/324aed92f8086f

2023-08-19 22:12 UTC, KitauchiRyota commented on features/MessageDialog.js
> +export default function MessageDialog({open,setOpen,onClickSend}){
引数で`open`や`setOpen`を渡すのは解消しましたが，かなり自分なりに解釈して修正してしまったかもしれません．

2023-08-19 22:13 UTC, KitauchiRyota commented on features/MessageDialog.js
> +              Please write a new reply here!
とりあえず文字の埋め込みで変更します・・・

2023-08-20 00:25 UTC, Wansuko-cmd requested changes
なんか小難しいことを言ってしまったかもしれないごめん
要は引数からsetOpenを消しちゃえばいいんじゃね？て話だったんよ
ほんでMessageDialogを使う側が操作する的な

ファイル複数あるとやりづらそうだし一つにしてくれると助かる

2023-08-20 00:25 UTC, Wansuko-cmd commented on features/MessageDialog.js
> +        <FloatActionButton src={addWhite} alt="add" onClickButton={handleOpen} />
float action buttonがここにあるのはまずそう
本来ならScreenにあるButtonが押されたときに稼働したりするはず

2023-08-20 00:25 UTC, Wansuko-cmd commented on features/MessageDialogNotUsingFAB.js
> +      setOpenDialog(false);
このsetOpenDialogって認識されるのか・・・

2023-08-20 02:15 UTC, Wansuko-cmd approved these changes

2023-08-20 02:16 UTC, Wansuko-cmd commented
LGTM

2023-08-20 02:17 UTC, merged