読み込み中のグルグルを出す
prapro-ou/castella-frontend pull request #65
Opened 2023-08-24 23:24 UTC by KitauchiRyota

## チェックリスト

- [x] マージ元のブランチが正しいか(自分の作成したブランチか)
- [x] マージ先のブランチが正しいか(基本はmain)
- [x] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [x] プルリクエストの名前を変更する
- [x] 下の欄を埋める

# 概要
非同期処理の待機中にグルグルを出す

### 実装したところ
`app/destinations/[[...slugs]]/page.js`
`features/hooks/UseData.js`
`feature/components/LoadingScreen`

### 懸念点
- サーバーの関係？で動作確認ができない（多分？）のでコードを書いただけで**動作確認をしておりません**．**致命的なミスがあるかもしれません**．
- グルグルをそれぞれのスクリーンの真ん中に出したかったので，`LoadingScreen`も変更した点
- `useData`変更したら他のIssueとコンフリクトしちゃいませんか・・・？

### 関連するIssue([Closes #数字]で選択可能)
Closes #57

2023-08-24 23:27 UTC, KitauchiRyota commented
一応実装してみましたが，`useData`について理解が浅い点や，動作確認をしていない点で修正が多くなるかもしれません．
お忙しい中お手数をおかけしますがどうかよろしくお願いします．

2023-08-26 11:44 UTC, Wansuko-cmd commented
<img width="1440" alt="スクリーンショット 2023-08-26 20 42 02" src="https://github.com/prapro-ou/castella-frontend/assets/63241922/4ef40e23-cd20-4834-a235-8cc0e7cf4737">

動かした感じこうなってる
1. opacity(https://tailwindcss.com/docs/opacity)いじって、後ろがちょっと見える感じにしてほしい
2. （できるなら）右だけローディングっぽくしてくれると助かる

2023-08-26 11:47 UTC, Wansuko-cmd requested changes
Conflictが発生しそうなのはこちらで調整する感じでいきたい
この部分の修正をお願いします

2023-08-26 11:47 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +            <LoadingScreen isLoading={true} />
`<LoadingScreen isLoading={isLoadingThreads}>`

みたいにできそう？
後ろの部分は透過する感じでOK

2023-08-26 11:47 UTC, Wansuko-cmd commented on features/components/LoadingScreen.js
> +      <div className='m-auto bg-gray'>
[`visibility`](https://tailwindcss.com/docs/visibility)をいじることでisLoadingで消したりすることができそう

2023-08-27 00:38 UTC, Wansuko-cmd requested changes
この部分を修正してほしい

2023-08-27 02:45 UTC, Wansuko-cmd approved these changes

2023-08-27 02:46 UTC, merged