Tipsを画面に出す
prapro-ou/castella-frontend pull request #67
Opened 2023-08-25 23:08 UTC by 1daLearn

## チェックリスト

- [ ] マージ元のブランチが正しいか(自分の作成したブランチか)
- [ ] マージ先のブランチが正しいか(基本はmain)
- [ ] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [ ] プルリクエストの名前を変更する
- [ ] 下の欄を埋める

# 概要
ThreadsやMessageにデータがない場合はTipsが出るようにした
### 実装したところ
1.送信相手がクリックされるとmessageIdを初期化
2.messageIdが初期化されているときMessageScreenはTipsを返す
3.Threadが空の時，MessageScreenを覆う大きさのThreadScreenがTipsを返す
Z-indexによりThreadはMessageの上にくる
### 懸念点
z-indexの設定がThreadScreenとMessageScreenでまたがっているため，page.jsでまとめて設定できるようにしたほうが良いかもしれない
### 関連するIssue([Closes #数字]で選択可能)

2023-08-25 23:16 UTC, 1daLearn commented
MessageIdやTipsが定義されていないというエラーですが，どうすればいいのか分かりません．

2023-08-26 11:53 UTC, Wansuko-cmd requested changes
一旦この部分の修正をお願いしたい

2023-08-26 11:53 UTC, Wansuko-cmd commented on features/messages/components/MessageScreen.js
> +    {messageId === false ? (
これは何を参照しようとした感じ？

2023-08-26 11:53 UTC, Wansuko-cmd commented on features/threads/components/ThreadScreen.js
> +    <div style={{ zIndex: 1 }}>
tailwindを利用して欲しい

2023-08-26 11:53 UTC, Wansuko-cmd commented on features/threads/components/ThreadScreen.js
> +      <Tips />
Tipsのimport文がないと思う

2023-08-26 13:02 UTC, 1daLearn commented on features/messages/components/MessageScreen.js
> +    {messageId === false ? (
UseData.jsにあるmessageIdです

2023-08-26 13:08 UTC, 1daLearn commented on features/messages/components/MessageScreen.js
> +    {messageId === false ? (
page.js内で，onClickDMTileのときsetMessageId(false);が呼ばれるので，それを条件分岐に使おうとしました

2023-08-26 15:29 UTC, Wansuko-cmd requested changes
ここを修正してほしい

2023-08-26 15:29 UTC, Wansuko-cmd commented on features/messages/components/MessageScreen.js
> +    {messageId === false ? (
引数にないからmessageIdは呼び出せないと思う
messagesがundefindかどうかで判別してもいいかと思う

2023-08-26 15:29 UTC, Wansuko-cmd commented on features/threads/components/ThreadScreen.js
> +    {threads.length === 0 ? (
- message版と判別方法が違う
- length === 0 だと単純にメール件数が0の時もTipsが表示されてしまってわかりづらい
ので直して欲しい

2023-08-26 15:29 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +          }}
これってなんで変更したとかある？

2023-08-26 15:38 UTC, 1daLearn commented on app/destinations/[[...slugs]]/page.js
> +          }}
送信相手がクリックされるとmessageIdを初期化したかったので，DMタイルがクリックされたときにDMIdと同時にMessageIdを初期化すればいいかなと考えました．
初期値といえばfalseかな思っていましたが今思うと変かもしれません．

2023-08-27 00:30 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +          }}
初期化の処理はsetSelectedDMIdでやってる（messagesがundefinded）からやらなくて良さそう

2023-08-27 02:55 UTC, Wansuko-cmd commented
LGTM
useDataの方との兼ね合い（マージなど）があるからそこを俺がやっちゃってもいい？

2023-08-27 03:03 UTC, 1daLearn commented
お願いします

2023-08-28 13:51 UTC, Wansuko-cmd approved these changes

2023-08-28 17:17 UTC, merged