useDataのリファクタリング
prapro-ou/castella-frontend pull request #68
Opened 2023-08-27 08:43 UTC by Yuto-Kambara

## チェックリスト

- [ ] マージ元のブランチが正しいか(自分の作成したブランチか)
- [ ] マージ先のブランチが正しいか(基本はmain)
- [ ] 不必要なコードを削除する(コマンドラインからPushする場合)
- [ ] lintを実行する（npm run format）
- [ ] プルリクエストの名前を変更する
- [ ] 下の欄を埋める

# 概要
useDataを理解しやすくするためにuseDestination,useThreads,useMessagesの三つに分解した
### 実装したところ
feature/destinations/component, feature/Threads/component, feature/Messages/component, app/destination
### 懸念点
use○○系に引数を渡して良いのか分からない
### 関連するIssue([Closes #数字]で選択可能)
issue #58

2023-08-27 09:22 UTC, Wansuko-cmd requested changes
一旦この部分の修正をお願いしたい

2023-08-27 09:22 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +    useDistinations(setIdMessageId);
これ引数はいらないかな
あくまでDestinationとしての役割をするだけで、わざわざそこまでする必要はないかと

2023-08-27 09:22 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +    useDistinations(setIdMessageId);
この処理は40行目にあるonClickDMTileに関数を渡すときにやるべきだと思う

2023-08-27 09:22 UTC, Wansuko-cmd commented on features/destinations/components/useDistinations.js
> +export default function useDistinations(setIdMessagesId) {
Destinationsにしてもらえると

2023-08-27 09:22 UTC, Wansuko-cmd commented on features/threads/components/useThreads.js
> +  const [, , setIds] = useMessages();
これはいらなそう？

2023-08-27 09:28 UTC, Yuto-Kambara commented on features/destinations/components/useDistinations.js
> +export default function useDistinations(setIdMessagesId) {
これってuseThreadsとかuseMessagesにも同じような変更加えたりしますか?

2023-08-27 09:33 UTC, Yuto-Kambara commented on features/threads/components/useThreads.js
> +  const [, , setIds] = useMessages();
これっていうのはsetIdsの部分でしょうか

2023-08-27 09:41 UTC, Wansuko-cmd commented on features/threads/components/useThreads.js
> +  const [, , setIds] = useMessages();
というかuseMessages自体がいらないかなと思ってる

2023-08-27 09:41 UTC, Wansuko-cmd commented on features/destinations/components/useDistinations.js
> +export default function useDistinations(setIdMessagesId) {
というより命名を変えて欲しくて
Distinations -> Destinations

2023-08-27 09:52 UTC, Yuto-Kambara commented on features/destinations/components/useDistinations.js
> +export default function useDistinations(setIdMessagesId) {
あぁスペルミスしてたんですね直しておきます

2023-08-27 10:08 UTC, Yuto-Kambara commented on features/threads/components/useThreads.js
> +  const [, , setIds] = useMessages();
ということはuseThreadと同じようにpage.jsの部分でsetIdsは使うということでしょうか

2023-08-27 11:24 UTC, Yuto-Kambara commented on app/destinations/[[...slugs]]/page.js
> +    useDistinations(setIdMessageId);
onClickDMTileに関数を渡すときにやるというのがちょっと分からないので教えていただけませんか

2023-08-27 13:48 UTC, Wansuko-cmd commented on features/threads/components/useThreads.js
> +  const [, , setIds] = useMessages();
そういう感じで頼みた

2023-08-27 13:52 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +    useDistinations(setIdMessageId);
```
          <DestinationScreen
            destinations={destinations}
            onClickAddButton={() => setOpenCreateDMDialog(true)}
            onClickDMTile={setSelectedDMId}
          />
```

今`page.js`はこんな感じだと思う

これをこんな感じに描けるようにしていくといいかも

```
          <DestinationScreen
            destinations={destinations}
            onClickAddButton={() => setOpenCreateDMDialog(true)}
            onClickDMTile={(dmId) => {
                setSelectedDMId(dmId); // useDestinationsから取得した関数
                setDMId(dmId); // useThreadsから取得した関数
            }}
          />
```

2023-08-27 17:52 UTC, Wansuko-cmd requested changes
いい感じにできてきたと思う
この部分の修正を頼みたい

2023-08-27 17:52 UTC, Wansuko-cmd commented on features/destinations/components/useDestinations.js
> +  const [dmId, setDMId] = useState();
これはいらなさそう？

2023-08-27 17:52 UTC, Wansuko-cmd commented on features/messages/components/useMessages.js
> +    setMessageId(messageId);
こんな感じに関数で囲まなくても単純に`setMessageId`を(返り値として)渡すようにしたらOK

2023-08-27 17:52 UTC, Wansuko-cmd commented on features/messages/components/useMessages.js
> +    setDMId(dmId);
こんな感じに関数で囲まなくても単純に`setDMId`を(返り値として)渡すようにしたらOK

2023-08-27 17:52 UTC, Wansuko-cmd commented on features/destinations/components/useDestinations.js
> +    setDestinations({ dms: newDMs, groups: [] });
この処理はuseEffectでしていることと同じだからまとめてもOK

2023-08-27 17:52 UTC, Wansuko-cmd commented on app/destinations/[[...slugs]]/page.js
> +            setDMIds(dmId);
そうそう、そんな感じ

2023-08-27 17:52 UTC, Wansuko-cmd commented on features/threads/components/useThreads.js
> +  const [messageId, setMessageId] = useState();
これいらなそう？

2023-08-28 13:16 UTC, Wansuko-cmd commented
すまん、やっちゃうで

2023-08-28 13:17 UTC, Wansuko-cmd approved these changes

2023-08-28 13:18 UTC, merged

2023-08-28 17:49 UTC, Yuto-Kambara commented
確認が遅れてしまってすみません。ありがとうございます。